### ISSUE TITLE
the raw file from githubusercontent.com doesn't play

### ISSUE THREAD

**Issue by HighPriest** [irth/codescream#1]
You gave us this link:
https://raw.githubusercontent.com/irth/codescream/main/codescream/scream1.wav

But it doesn't play for me because of CSP:

> Refused to load media from 'https://raw.githubusercontent.com/irth/codescream/main/codescream/scream1.wav' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by irth** [comment]
Feel free to re-host it somewhere if you want to use it. Or you could record your own scream, it's fun!
